export const SELECT_NOTE = 'SELECT_NOTE';
export const CLEAR_SELECT_NOTE = 'CLEAR_SELECT_NOTE';
export const UPDATE_NOTE = 'UPDATE_NOTE';
export const MOVE_SELECTED_NOTE = 'MOVE_SELECTED_NOTE';
export const ADD_BLOCK = 'ADD_BLOCK';
export const REMOVE_BLOCK = 'REMOVE_BLOCK';
export const EXPORT_TAB_TXT = 'EXPORT_TAB_TXT';
